name: Events

on:
  schedule:
    # run at 7AM every single day
    # https://crontab.guru <-- for generating CRON expression
    - cron: "0 5 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: ./
  DBT_PG_USR: ${{ secrets.DBT_POSTGRES_USERNAME }}
  DBT_PG_PWD: ${{ secrets.DBT_POSTGRES_PWD }}
  DBT_PG_HOST: ${{ secrets.DBT_POSTGRES_HOST }}
  DBT_PG_DB: ${{ secrets.DBT_POSTGRES_DB }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"

      - name: Install dependencies and run dbt
        working-directory: reimagined_chainsaw
        run: |
          pip install --upgrade pip
          pip install dbt-redshift
          dbt deps
          dbt seed
          dbt run
          dbt test
